### ISSUE TITLE
License

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/repro#13]
repro needs a proper license - say, a permissive license like MIT?

**Comment by aaronpeikert** [comment]
Thank you for the suggestion, indeed I already choose to use MIT, but licenses for r packages require a different scheme then normally for GitHub.
see https://github.com/aaronpeikert/repro/blob/a20ff6688aef775aead959bd1351f78c39767fcd/DESCRIPTION#L27
and 
the LICENSE.md file.
