### ISSUE TITLE
think about codebooks

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro#22]
I don't know if I should incorporate this in `repro` or leave it in worcs.

**Comment by cjvanlissa** [comment]
Recommend putting it in repro. I think this codebook functionality is, tbh, much more lightweight and at least as good as `codebook` or `dataMaid`. Especially if we develop the metadata component we discussed today.

**Comment by aaronpeikert** [comment]
ok then #23 
If this grows out of proportion, with the metadata and stuff, we still can move it to its own package.
