### ISSUE TITLE
What should I modify in `.dockerignore`?

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro#62]
Singling out @hille's question in #61 in its own issue.

**Comment by aaronpeikert** [comment]
To understand what the `.dockerignore` is, we must understand what the docker build context is.
When we build a docker image, it has access to everything in the build folder. However, if these files are super large, this can have performance issues. Also, if there is sensitive information lying around, it could get exposed.

So it is pretty much äquivalent to the `.gitignore`, just for docker :information_source: 

Take a look at:

https://docs.docker.com/engine/reference/builder/#dockerignore-file
https://codefresh.io/docker-tutorial/not-ignore-dockerignore-2/

**Comment by aaronpeikert** [comment]
@hille is this clear?

**Comment by hille** [comment]
So to be sure that I understood it correctly: It is optional to modify the ```.dockerignore ```, but recommended if files are large and one would like to optimize performance?

**Comment by aaronpeikert** [comment]
You got it!
