### ISSUE TITLE
`brew cask install docker` not working

### ISSUE THREAD

**Issue by Maplessss** [aaronpeikert/repro#92]
`repro::check_docker()` leads to the advice to insert `brew cask install docker` in an admin terminal. This does not install Docker, though, but results in "Error: Unknown command: cask". 

The actual command, according to https://formulae.brew.sh/cask/docker, should be `brew install --cask docker`,

**Comment by aaronpeikert** [comment]
Thank you so much, not only for opening an issue but also for finding the correct solution. Greatly appreciated.

**Comment by Maplessss** [comment]
Thank you for creating this greatly helpful package!
